import type { Metadata } from "next";
import { Roboto_Mono, Bebas_Neue } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import Alerts from "@/components/ui/alerts";

const roboto = Roboto_Mono({ subsets: ["latin"] });
const bebas = Bebas_Neue({ subsets: ["latin"], weight: "400", variable: "--font-bebas" });

export const metadata: Metadata = {
  title: "Bordeable - Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={clsx(roboto.className, bebas.variable)}>
        {children}
        <Alerts />
      </body>
    </html>
  );
}
